# Generated by Django 4.1.7 on 2023-04-23 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homework_created_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homework',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='homework',
            name='homework_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.lesson'),
        ),
    ]
