# Generated by Django 4.1.7 on 2023-04-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lesson_homework_done_homework_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='homework_type',
            new_name='lesson',
        ),
    ]
